namespace PL051.NStar;

[Flags]
public enum TypeAttributes
{
	None = 0,
	Sealed = 1,
	Abstract = 2,
	Static = 3,
	Struct = 4,
	Enum = 5,
	Interface = 6,
	Delegate = 7,
	Private = 16,
	Protected = 32,
	Internal = 64,
	Partial = 256,
}

[Flags]
public enum PropertyAttributes
{
	None = 0,
	Static = 1,
	Private = 2,
	Protected = 4,
	Internal = 8,
	Const = 16,
	NoSet = 32,
	SetOnce = 64,
	PrivateSet = 128,
	ProtectedSet = 256,
	Required = 512,
}

[Flags]
public enum ConstantAttributes
{
	None = 0,
	Static = 1,
	Private = 2,
	Protected = 4,
	Internal = 8,
}

[Flags]
public enum FunctionAttributes
{
	None = 0,
	Static = 1,
	Private = 2,
	Protected = 4,
	Internal = 8,
	Const = 16,
	Multiconst = 32,
	Abstract = 64,
	Sealed = 128,
	New = 192,
	Async = 256,
	IO = 512,
	Extent = 1024,
	Wrong = -2147483648,
}

[Flags]
public enum ParameterAttributes
{
	None = 0,
	Optional = 1,
	Ref = 2,
	Out = 4,
	Params = 6,
}

[Flags]
public enum ConstructorAttributes
{
	None = 0,
	Static = 1,
	Private = 2,
	Protected = 4,
	Internal = 8,
	Multiconst = 16,
	Abstract = 32,
	AutoGenerated = 64,
}

public enum BlockType : byte
{
	Unnamed,
	Primitive,
	Extra,
	Namespace,
	Class,
	Struct,
	Interface,
	Delegate,
	Enum,
	Function,
	Constructor,
	Destructor,
	Operator,
	Extent,
	Other,
}

public enum TypeConstraints : byte
{
	None,
	BaseClassOrInterface,
	BaseInterface,
	NotAbstract,
	EnumType,
}

public enum RawStringState : byte
{
	Normal,
	ForwardSlash,
	Quote,
	ForwardSlashAndQuote,
	EmailSign,
}
