<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<!--If you are willing to use Windows/MacOS native APIs you will need to create 3 projects.
	One for Windows with net10.0-windows TFM, one for MacOS with net10.0-macos and one with net10.0 TFM for Linux.-->
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<BuiltInComInteropSupport>true</BuiltInComInteropSupport>
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<RunPostBuildEvent>OnOutputUpdated</RunPostBuildEvent>
	</PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="..\PL051.NStar\PL051.NStar.csproj" />
		<Reference Include="RedStarMath">
			<HintPath>..\BuiltInMemberCollections\packages\RedStarMath.dll</HintPath>
		</Reference>
		<Reference Include="RedStarMath.Complex">
			<HintPath>..\BuiltInMemberCollections\packages\RedStarMath.Complex.dll</HintPath>
		</Reference>
	</ItemGroup>

	<Target Name="MyPostPublish" AfterTargets="Publish">
		<Exec Command="copy &quot;$(SolutionDir)\PL051.NStar\packages\dotnet.7z&quot; &quot;$(PublishDir)\dotnet.7z&quot; /Y" />
	</Target>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<Exec Command="copy &quot;$(SolutionDir)\PL051.NStar\packages\dotnet.7z&quot; &quot;$(TargetDir)\dotnet.7z&quot; /Y" />
	</Target>
</Project>
